import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Target Sistemas Desafio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Bem vindo ao desafio da <a target='_blank' href="https://targetsistemas.com.br/">Target Sistemas</a>
        </Title>

        <Description>
          Desafio de programação para estágio na Target Sistemas, por <a target={'_blank'} href="https://arthur-candido.vercel.app/">Arthur Candido</a>
        </Description>

        <Cards name='Fibonacci' url='/fibonacci' />
        <Cards name='Controle De Faturamento' url='/controle_de_faturamento' />
        <Cards name='Faturamento por Estado' url='/faturamento_por_estado' />
        <Cards name='Inverson de Strings' url='/inversor_de_strings' />
      </Main>
    </Container>
  )
}
